### ISSUE TITLE
大佬想加新的搜索图标要怎么添加

### ISSUE THREAD

**Issue by 602293544** [zzd/Simple-Search-Page#3]

**Comment by 602293544** [comment]
https://fsou.cc/

这个的图标

**Comment by zzd** [comment]
`public/json/search_engine.json` 这个文件

**Comment by 602293544** [comment]
{
"url": "https://fsou.cc/",
"icon": "icon-favicon",
"text": "F 搜"
},

下载的1.4.2的哪个  然后看不懂

**Comment by zzd** [comment]
`1.x` 已经不维护了，我说的是 `3.0Vue` 版本修改方式。

**Comment by 602293544** [comment]
难过😔😔😔

**Comment by zzd** [comment]
你可以修改编译3.0版本

**Comment by 602293544** [comment]
不会没学过   😁😁😁😁
